# Generated by Django 4.1.1 on 2022-09-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0002_delete_ingredients_delete_purchase_menu_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="image",
            field=models.ImageField(default=None, upload_to=""),
        ),
    ]
