# Generated by Django 4.1.1 on 2022-09-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0003_menu_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="image",
            field=models.ImageField(default=None, upload_to=None),
        ),
    ]
