# Generated by Django 4.1.1 on 2022-09-24 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0004_alter_menu_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="menu", name="image",),
    ]
