# Generated by Django 4.1.1 on 2022-09-25 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0006_ingredients_menu_ingred"),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchased",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField(default=20)),
                ("amount", models.IntegerField(default=20)),
                (
                    "order",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipe.menu",
                    ),
                ),
            ],
        ),
    ]
